name: stagiaire
description: My internship Application as a memory of good time

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^0.1.26      #  latest version of curved nav-bar

  flutter_staggered_grid_view: ^0.2.7  #For Tu Kiffes ou pas

  url_launcher: ^5.0.2

  video_player: ^0.10.5+2

  cached_network_image: ^0.7.0
  sentry: ^2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.6.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Here I set the icon for both Android and Ios

flutter_icons:
  image_path: "images/logo_launcher.gif"
  android: true
  ios: true


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/logo.png
    - assets/images/logo_animated.gif
    - assets/images/home.jpg
    - assets/images/home1.jpg
    - assets/images/logo_launcher.png
    - assets/avatars/avatar-1.jpg
    - assets/avatars/avatar-2.jpg
    - assets/avatars/avatar-3.jpg
    - assets/avatars/avatar-4.jpg
    - assets/avatars/avatar-5.jpg
    - assets/avatars/avatar-6.jpg
    - assets/laposte1.jpg
    - assets/laposte2.jpg
    - assets/laposte3.jpg
    - assets/laposte4.jpg
    - assets/ensim1.png
    - assets/ensim2.png
    - assets/maphoto.jpg
    - assets/img/victory.png
    - assets/img/progress_0.png
    - assets/img/progress_1.png
    - assets/img/progress_2.png
    - assets/img/progress_3.png
    - assets/img/progress_4.png
    - assets/img/progress_5.png
    - assets/img/progress_6.png
    - assets/img/progress_7.png
    - assets/hang_images/img/victory.png
    - assets/hang_images/img/progress_0.png
    - assets/hang_images/img/progress_1.png
    - assets/hang_images/img/progress_2.png
    - assets/hang_images/img/progress_3.png
    - assets/hang_images/img/progress_4.png
    - assets/hang_images/img/progress_5.png
    - assets/hang_images/img/progress_6.png
    - assets/hang_images/img/progress_7.png
    - assets/LaPosteImages/POSTE/GroupeLaPoste/histoire1.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/avant91.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/laposte2010.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/laposte2015.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/laposte.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/avenir2.png
    - assets/LaPosteImages/POSTE/GroupeLaPoste/chiffres.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/activite.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/avenir3.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/lesaviezvous1.jpg
    - assets/LaPosteImages/POSTE/GroupeLaPoste/logo1.png
    - assets/LaPosteImages/POSTE/GroupeLaPoste/logo2.png
    - assets/LaPosteImages/POSTE/GroupeLaPoste/logo3.png
    - assets/LaPosteImages/POSTE/GroupeLaPoste/logo4.png
    - assets/LaPosteImages/POSTE/GroupeLaPoste/logo5.png
    - assets/LaPosteImages/POSTE/GroupeLaPoste/logo6.png
    - assets/LaPosteImages/POSTE/PicSaintPriest/logistique.jpg
    - assets/LaPosteImages/POSTE/PicSaintPriest/mtigf1.jpg
    - assets/LaPosteImages/POSTE/PicSaintPriest/mtigf2.jpg
    - assets/LaPosteImages/POSTE/PicSaintPriest/mtipf1.jpg
    - assets/LaPosteImages/POSTE/PicSaintPriest/manuel.jpg
    - assets/LaPosteImages/POSTE/PicSaintPriest/posteaero.jpg
    - assets/LaPosteImages/POSTE/PicSaintPriest/lependu1.jpg
    - assets/LaPosteImages/tgvpostal.jpg
    - assets/LaPosteImages/STAGE/MachinesUtilisees/bacs1.jpg
    - assets/LaPosteImages/POSTE/PicSaintPriest/pic_site.png
    - assets/LaPosteImages/POSTE/PicSaintPriest/pic_plan1.png
    - assets/LaPosteImages/POSTE/PicSaintPriest/parcours.png
    - assets/LaPosteImages/STAGE/MachinesUtilisees/bacs1.jpg
    - assets/LaPosteImages/STAGE/MachinesUtilisees/brin.png
    - assets/LaPosteImages/STAGE/MachinesUtilisees/kub.jpg
    - assets/LaPosteImages/STAGE/MachinesUtilisees/ke7.jpg
    - assets/LaPosteImages/STAGE/MachinesUtilisees/bak.jpg
    - assets/LaPosteImages/STAGE/MachinesUtilisees/cv300.png
    - assets/LaPosteImages/STAGE/MachinesUtilisees/ce30.png
    - assets/LaPosteImages/STAGE/MesMissions/uniforme.png
    - assets/LaPosteImages/STAGE/MesMissions/gilet.png
    - assets/LaPosteImages/STAGE/MesMissions/chaussure.jpg
    - assets/LaPosteImages/STAGE/MesMissions/mesactivites.jpg
    - assets/LaPosteImages/STAGE/MesMissions/autres.png
    - assets/LaPosteImages/STAGE/JourneeType/intro.jpg
    - assets/LaPosteImages/STAGE/JourneeType/reveil.jpg
    - assets/LaPosteImages/STAGE/JourneeType/metro.jpg
    - assets/LaPosteImages/STAGE/JourneeType/bus.jpg
    - assets/LaPosteImages/STAGE/JourneeType/reunion.jpg
    - assets/LaPosteImages/STAGE/JourneeType/friday.jpg
    - assets/LaPosteImages/STAGE/ResumeStage/francais.jpg
    - assets/LaPosteImages/STAGE/ResumeStage/england.jpg
    - assets/LaPosteImages/STAGE/ResumeStage/enroute.jpg
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
